create table ingredients (
    id bigint generated by default as identity primary key,
    ingredient_name varchar(50) unique not null,
    leftover integer not null
);

create table drinks (
    id bigint generated by default as identity primary key,
    drink_name varchar(50) not null,
    price int not null,
    order_count bigint default 0
);

create table recipes (
    drink_id bigint not null references drinks(id),
    ingredient_id bigint not null references ingredients(id),
    amount int not null,
    primary key (drink_id, ingredient_id)
);


create table orders (
    id bigint generated by default as identity primary key,
    drink_id bigint not null references drinks(id),
    order_time timestamp default current_timestamp
);



